### ISSUE TITLE
Popup broken in upcoming Plasma 5.26

### ISSUE THREAD

**Issue by thelaughinggnome** [blackadderkate/weather-widget-2#109]
Plasma applet popups are now resizable, but need to be updated for this new functionality. The graph is currently very broken.

See: https://invent.kde.org/frameworks/plasma-framework/-/merge_requests/500 and https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/1688

![Screenshot_20220911_011039](https://user-images.githubusercontent.com/113253565/189492035-37a76e49-85d4-47a7-80b7-5ed3b157cfd4.jpg)

**Comment by galibozek** [comment]
I confirm today the stable Plasma 5.26 was released :/

**Comment by galibozek** [comment]
@blackadderkate is it possible to set default width and height?

**Comment by idamir** [comment]
At least Layout.minimumWidth and Layout.minimumHeight should be set like
`Layout.minimumWidth: PlasmaCore.Units.gridUnit * 22`
`Layout.maximumWidth: PlasmaCore.Units.gridUnit * 80`
`Layout.minimumHeight: PlasmaCore.Units.gridUnit * 22`
`Layout.maximumHeight: PlasmaCore.Units.gridUnit * 40`
The numeric constants must be found before.

**Comment by galibozek** [comment]
@idamir will you make a patch?

**Comment by FSKMTM** [comment]
Changing "width" and "height" to "implicitWidth" and "implicitHeight" in lines 39 and 40 of "FullRepresentation.qml" scales the popup properly. Doesn't make it resizable, though.

**Comment by galibozek** [comment]
@FSKMTM thanks, it works :)

**Comment by idamir** [comment]
pr #113

**Comment by blackadderkate** [comment]
Thanks @idamir & @FSKMTM for looking into this for me.

I haven't managed to upgrade my ArchLinux development box to Plasma 5.26 yet - been busy with work and family issues. I'm hoping to get it upgraded on Saturday, so I can work on making the widget properly resizeable.

**Comment by fkru** [comment]
@blackadderkate: After upgrading to KDE Plasma 5.26 I am also hit by this bug. The fix should reach KDE Store (https://store.kde.org/p/1683743) as well, since there are lot's of people not updating via github. Thx.

**Comment by blackadderkate** [comment]
> @blackadderkate: After upgrading to KDE Plasma 5.26 I am also hit by this bug. The fix should reach KDE Store (https://store.kde.org/p/1683743) as well, since there are lots of people not updating via github. Thx.

Don't worry, I'll be releasing a new version soon! You guys here on Github are my unofficial "Beta" testers - once you've found all the bugs I've missed then I upload a new version to the KDE store!

To be honest, I think I've got most of them squashed now, so I'll be uploading a new version there soon.
