### ISSUE TITLE
In the pop-up window there is a strange preamble for wind 

### ISSUE THREAD

**Issue by KVAnton-WEB** [blackadderkate/weather-widget-2#12]
![изображение](https://user-images.githubusercontent.com/12401787/149600860-4cc0c3d7-f7f8-4e25-8005-130f9371f80a.png)
This is an OWM source if it matters

**Comment by blackadderkate** [comment]
OK - I think I know what the problem is. I am stupid!
I use an icon to show which direction the wind is coming from, but the code only works when the wind direction is in English.

This might take me a few hours to fix...

**Comment by blackadderkate** [comment]
I am fairly sure I have fixed it - can you please [download the new version from here](https://github.com/blackadderkate/weather-widget-2/releases/download/v2.0.3/weather-widget-2.plasmoid) and give it a try before I publish it on the KDE store?
Thanks.

**Comment by KVAnton-WEB** [comment]
![изображение](https://user-images.githubusercontent.com/12401787/149628779-c4fb6511-18f3-42f8-85b7-1a7191a0a5b0.png)

master commit 43cd505ef66144c1a6947c486383846f44b1c2c5

**Comment by blackadderkate** [comment]
Yes, that looks much better!
