### ISSUE TITLE
Does it still make sense to use original applet from Kotelnik?

### ISSUE THREAD

**Issue by bam80** [blackadderkate/weather-widget-2#125]
Or we can just burn it with fire?

**Comment by blackadderkate** [comment]
I'm not sure if I understand the question.

If you are referring to the branding I've put on the KDE Store and here on Github, then I still want to give Kotelnik the appropriate credit - after all the widget is still ~ 90% their original code.

If you are asking whether you should install the original version still listed on the KDE store and use it, probably not...

**Comment by bam80** [comment]
I asked the latter question, thanks.

**Comment by bam80** [comment]
It just made some confusion as you repo is not marked as a fork, not sure why..

**Comment by blackadderkate** [comment]
> It just made some confusion as you repo is not marked as a fork, not sure why..

I had never used Github and had no idea what a Fork was at the time I released the updated widget - I was more used to the CVS checkin/checkout model of working. So I never described it as a fork, because I didn't know that's what it was!
