### ISSUE TITLE
The longitude and altitude in the configuration cannot be recognized properly

### ISSUE THREAD

**Issue by tjw123hh** [blackadderkate/weather-widget-2#139]
When I try to use more than 6 decimal places for latitude and longitude in a URL or transpose latitude and longitude with altitude in a URL, the weather is obtained normally, but the latitude, longitude and altitude in the configuration cannot be recognized properly , and the configuration interface becomes like this: 
![图片](https://user-images.githubusercontent.com/56749271/210320626-10524e92-5241-4acc-8aec-138e27c3d0b3.png)

**Comment by martin-ms** [comment]
This is not a bug. There is a limitation from Met.no, documented in their [Terms of Service](https://api.met.no/doc/TermsOfService#traffic), that the queries should be truncated to a maximum of 4 digits:

> When using requests with latitude/longitude, truncate all coordinates to max 4 decimals. There is no need to ask for weather forecasts with nanometer precision! For new products, requests with 5+ decimals will return a 403 Forbidden.

The widget respects these guidelines, so you should use the search results from the internal database for your location and not self-created values with significantly more digits.
