### ISSUE TITLE
 The precipitation histogram is floating 

### ISSUE THREAD

**Issue by tjw123hh** [blackadderkate/weather-widget-2#140]
![图片](https://user-images.githubusercontent.com/56749271/211228198-51d762f7-1150-4460-b3b5-e8aa0e24dddc.png)
 It's weird. 
 Shouldn't precipitation histograms be aligned to the bottom?

**Comment by blackadderkate** [comment]
No, I used that gap to display the units (mm). At the moment mm is the only option, but I'm hoping to add rainfall in inches for people who use imperial units if I can find a reasonable way to calculate and display fractions.
