### ISSUE TITLE
Compilation fails because of translations

### ISSUE THREAD

**Issue by Vistaus** [blackadderkate/weather-widget-2#15]
I tried to compile the widget, but it errors out:

```
CMake Error at CMakeLists.txt:18 (add_subdirectory):
  add_subdirectory given source "translations" which is not an existing
  directory.


CMake Warning at /usr/lib64/cmake/KF5Package/KF5PackageMacros.cmake:69 (message):
  warnings during generation of metainfo for org.kde.weatherWidget-2:
  kf.coreaddons: Invalid plugin metadata: Attempting to create a KAboutPerson
  from json without 'Name' property:
  QJsonObject({"Email":"kate.buckley@gmail.com"})

Call Stack (most recent call first):
  /usr/lib64/cmake/KF5Plasma/KF5PlasmaMacros.cmake:36 (kpackage_install_package)
  CMakeLists.txt:20 (plasma_install_package)


-- Configuring incomplete, errors occurred!
See also "/home/thefish/Downloads/weather-widget-2/build/CMakeFiles/CMakeOutput.log".
```

I tried adding the correct path of that directory to CMakeLists.txt, which is package/translations, but then it complains that the translations folder doesn't contain a CMakeLists.txt file.

**Comment by blackadderkate** [comment]
To be honest I've only been using it as a plasmoid - C++ and MakeLists make my head spin!
I've just uploaded a possible fix - it compiles and installs successfully, but I haven't tested whether the compiled widget actually works yet.

**Comment by Vistaus** [comment]
Thanks! That solved the compilation issue. However, translations aren't working.

**Comment by blackadderkate** [comment]
I have uploaded the missing CMakeLists.txt file to the translations folder, so it should compile now.
However I have spotted some issues with the translation files themselves, which I still need to upload - so you might want to wait until I've uploaded those...

**Comment by blackadderkate** [comment]
I have just been working on them, and pushed some updates.
Give them a try - I've just setup a test-user on my laptop with French Language settings, and the translations work for me (both as a plasmoid AND in the system tray).

![Screenshot_20220116_184652](https://user-images.githubusercontent.com/83865293/149673662-29a17116-cc2f-4b66-be34-fcf256546db5.png)
.

**Comment by blackadderkate** [comment]
I've just pushed a compilation script, and a load of translation updates.
Try running the dev_build.sh script - it works for me:

![Screenshot_20220116_184652](https://user-images.githubusercontent.com/83865293/149674024-972d355f-3b71-4a2a-a0e3-a125bdc5b951.png)

**Comment by Vistaus** [comment]
I can confirm that they are working now! Thanks for fixing all of this so quickly! 🙂

**Comment by blackadderkate** [comment]
Luckily it's the weekend, so I was able to do it quickly.

Thank you for your patience (and your rating on the KDE store). This is the first software I have ever released to the public, and there is so much to learn. I have already learnt that just because something works for me in English, it doesn't mean it will work for people in other languages! :-)
