### ISSUE TITLE
(Plasma 6 beta) MetNo sources not working for @als-creator

### ISSUE THREAD

**Issue by blackadderkate** [blackadderkate/weather-widget-2#164]
In this beta version the weather forecast from metno does not work, own works fine

![image](https://github.com/blackadderkate/weather-widget-2/assets/25702710/e2c7cd41-b2a4-4382-8047-f5277bbfdc21)

![image](https://github.com/blackadderkate/weather-widget-2/assets/25702710/637dae9e-8064-4b64-8433-c881654d9f7e)

_Originally posted by @als-creator in https://github.com/blackadderkate/weather-widget-2/issues/157#issuecomment-1981174003_

**Comment by blackadderkate** [comment]
@als-creator OK, I have setup an ArchLinux box, and the widget works for me on both OWM and MetNo sources:

![VirtualBox_ArchLinux_08_03_2024_19_42_16](https://github.com/blackadderkate/weather-widget-2/assets/83865293/c62715ef-7980-4884-b457-301d513d658c)
![VirtualBox_ArchLinux_08_03_2024_19_41_06](https://github.com/blackadderkate/weather-widget-2/assets/83865293/8e7fb329-77ed-4bf9-af16-7e3aae50b6e3)

It might be something related to the Cyrillic Language - or possibly timezone related?
I will investigate...

**Comment by als-creator** [comment]
Now I clicked on the widget and the forecast instantly updated before my eyes and now works in both cases, I don’t know the reason

![image](https://github.com/blackadderkate/weather-widget-2/assets/25702710/ce67a3c7-6a1b-4959-82bf-6e6443fca501)
![image](https://github.com/blackadderkate/weather-widget-2/assets/25702710/d1608aa5-0daa-4d11-8bf5-13c7719c6c60)
