### ISSUE TITLE
Issue: In Dark Breeze theme, the black letters on dark background

### ISSUE THREAD

**Issue by Mshmaitelly** [blackadderkate/weather-widget-2#168]
As seen in this screen
![weather_black_letters](https://github.com/blackadderkate/weather-widget-2/assets/13006192/a294d0c7-69d7-42b5-adff-f5d34ea9710c)

**Comment by blackadderkate** [comment]
Should be fixed in try the new [Beta2](https://github.com/blackadderkate/weather-widget-2/releases/download/3.0.0b2/weather-widget-3.0.0b2.plasmoid) I just uploaded.

You might need to remove the old version and/or logout and back in again.

**Comment by Mshmaitelly** [comment]
Removed the old versions.
I installed b2, now the chart cannot be displayed at all.

**Comment by blackadderkate** [comment]
OK, please run konsole and enter the following:

`plasmawindowed org.kde.weatherWidget-3`

and send me the output = there's probably a missing dependency or something...

**Comment by Mshmaitelly** [comment]
When I run the command, I got windowed version of th plasmoid. If I click on the window, I can see the chart. I will post the screenshot in the second comment. Here is the log of the plasmoid

![image](https://github.com/blackadderkate/weather-widget-2/assets/13006192/c0299ea1-2db6-49f0-b5b6-f3561959cf93)

**Comment by Mshmaitelly** [comment]
Click on the windowed version would show the graph
![image](https://github.com/blackadderkate/weather-widget-2/assets/13006192/7ac6e196-8c4a-49bb-9e2a-5dd5932d4af8)

**Comment by Mshmaitelly** [comment]
I figured out the problem. If the widget was in added from the status and notification by enabling the weather widget, you can cannot see the chart when you click on the weather icon. 
However, if you add the widget to the panel, then by clicking on the weather icon,  the chart is displayed.
Note today's weather values in the chart are still black on dark background.

**Comment by blackadderkate** [comment]
Ah, that explains it.
The code for running in the status and notification panel isn't fully implemented yet. I'll add that to the release notes.

**Comment by Mshmaitelly** [comment]
I rebooted, and it is working as a widget add tot the main panel
![image](https://github.com/blackadderkate/weather-widget-2/assets/13006192/7b0e7379-ac73-437a-828e-9014cb064ccd)

**Comment by blackadderkate** [comment]
OK, I've updated the release notes.
For what it's worth, the full graph was not displayed on the original plasma5 version either - I think there was a limit to the size or number of popups allowed in the system tray or something like that...
