### ISSUE TITLE
Disable text about last update

### ISSUE THREAD

**Issue by ShalokShalom** [blackadderkate/weather-widget-2#176]
This purple text, that supposedly shows when the app was last updated with new information, can currently not be disabled. 

This is a suggestion, to make this possible. 
The text is sometimes in the way:

![Screenshot_20240405_205228](https://github.com/blackadderkate/weather-widget-2/assets/6344099/e393524c-46c8-47cc-9768-52ad97348287)

**Comment by jotapesse** [comment]
Better than being disabled, IMO it shoudl be kept to one line only at the bottom and with a lower size font. The "disable" option could be a nice thing to have but shouldn't be regarded as a solution for this issue.

**Comment by evgeniy-harchenko** [comment]
If you want, you can test my latest (test) widget [version](https://github.com/evgeniy-harchenko/weather-widget-2/tree/draft). It has fix for this problem.

**Comment by ShalokShalom** [comment]
I do like to disable it at all

**Comment by blackadderkate** [comment]
OK, this has been fixed in Pull Request #177.
I've also pushed commit 8b81763 so the text is elided rather than wrapped so the text no longer wraps over multiple lines.
[Download Release v3.0.4 here](https://github.com/blackadderkate/weather-widget-2/releases/tag/V3.0.4)

**Comment by ShalokShalom** [comment]
Sorry, this does not fix the issue. 🙁

**Comment by evgeniy-harchenko** [comment]
I made PR with fixes from my draft branch. I believe it will work as it should now: https://github.com/blackadderkate/weather-widget-2/pull/178/commits/09e58fda0b5ac32c344c5efb1ab9937fba37e900
