### ISSUE TITLE
Graphs not rendering properly.

### ISSUE THREAD

**Issue by AyushRawal** [blackadderkate/weather-widget-2#18]
Some lines are rendered twice in the owm graph and all lines are rendered twice in metno graph which makes the whole thing cramped and incomprehensible.
![Screenshot_20220125_080630](https://user-images.githubusercontent.com/32910415/150900929-ba0e9444-1755-4dbc-b463-f956e96570bc.png)
![Screenshot_20220125_081149](https://user-images.githubusercontent.com/32910415/150901038-4bf98d67-925f-435f-abd7-e8050477a4b5.png)
I had the same issue with the original plasma weather widget.

Btw, thanks for this awesome widget !

**Comment by blackadderkate** [comment]
That is so weird - I've been using this widget for years and have never seen anything like this!

The only thing I can think of is that it is timezone-related - India is 5½ hours ahead of GMT, perhaps the ½ hour affects the way the graph calculates where all the lines and icons should be?

The simplest way to check would be to change the timezone on your computer to GMT, run the widget with plasmoidviewer (or logout and back in again) and see if the problem goes away.

To run the widget with plasmoidviewer, use the following command:
plasmoidviewer -a ~/.local/share/plasma/plasmoids/org.kde.weatherWidget-2

**Comment by AyushRawal** [comment]
That is indeed the case here.  I was trying to debug the issue and found the reason of the problem.
 https://github.com/blackadderkate/weather-widget-2/blob/2fa8fe9565a259d068ede2fdb12d24664f31ede8/package/contents/ui/Meteogram.qml#L72-L103

Here, `dateForm` is rounded down to hours but not `dateTo`, which causes the difference between them to be 1:30 hours in my timezone, which is then rounded up by `Math.round()` and thus an extra iteration in the for loop at line 87 and hence extra lines in the graph.

The solution would be to use `Math.floor()` instead of `Math.round()`.
I am creating a pull request that fixes it.

Cheers

**Comment by AyushRawal** [comment]
#23
