### ISSUE TITLE
Downloaded version 2.1.4 from KDE store, but  it shows up only in the system tray, which has a different compact layout. What do I miss? Any idea? Thx.

### ISSUE THREAD

**Issue by blackadderkate** [blackadderkate/weather-widget-2#25]
Downloaded version 2.1.4 from KDE store, but  it shows up only in the system tray, which has a different compact layout. What do I miss? Any idea? Thx.

_Originally posted by @fkru in https://github.com/blackadderkate/weather-widget-2/issues/6#issuecomment-1022235120_

**Comment by blackadderkate** [comment]
Not sure what's going on there to be honest.

Just out of curiosity, can you please try creating a New Panel, and adding the widget there - or adding the widget to your desktop - and check whether the full view appears (with the Meteogram graph) and whether changing the display layout to Vertical / Compact works as it should?

**Comment by fkru** [comment]
openSUSE Tumbleweed 20220124
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0

**Comment by fkru** [comment]
So, the issue is solved: When downloading your widget to add it, e.g., to the desktop it immediately shows up in the system tray not on the desktop. However, if I choose again "add widget" I am able to install it on the deskop or the panel. Sorry for the noise. Strange anyway.

**Comment by blackadderkate** [comment]
OK, that makes sense.
I will turn off the setting "X-KDE-PluginInfo-EnabledByDefault" to prevent it from automatically adding itself to the System Tray.
