### ISSUE TITLE
The translations are not compiled during the compile stage

### ISSUE THREAD

**Issue by solbu** [blackadderkate/weather-widget-2#36]
Hi.
I have been tracking down an rpmbuild warning that turns out to be from the way translations are handled.
The «CMakeFiles.txt» in the translations folder seaches for the «.po» files in the none existing subfolder «po/».

When I change my spec file (rpm packaging) to move all «.po» files from «package/translations/» into «package/translations/po/», and _also_ forcibly deletes the «package/contents/locale/» folder then cmake does find and compile the translations and they are installed into the correct place during the «make install» stage.

If you look at the original project, the po files are in a separate po folder in the translations folder.
Doing this change makes the distribution packages installing everything in the correct place.

I havent made the norwegian translation work yet (I copied it from the master bransh for my local testing)
It might be due to the fact that there are still 2 places where it uses the old project name.
You can find them with «git grep "kde.weatherWidget"»

**Comment by blackadderkate** [comment]
If I remember correctly, I had trouble getting translations to work when it was installed as a Widget into a users' ~/.local/plasma/plasmoid folder using "Add Widget" or from the KDE Store. 

So I went to the KDE website and [followed their translation documentation](https://develop.kde.org/docs/extend/plasma/widget/translations-i18n) including [their Folder Structure](https://develop.kde.org/docs/extend/plasma/widget/translations-i18n/#translation-folder-structure).

Looks like that broke the Dev build script...

**Comment by solbu** [comment]
The fix I'm preparing for a Pull Request will accomodate both worlds. :-)
The make install step will install into the system wide «/usr/share/locale/» folder, and i have tested that translations work when packaged by a distro.
And the «create-plasmoid-package.sh» script creates everything, including the translations.

**Comment by blackadderkate** [comment]
I was looking at package/translations/CMakeList.txt - I think changing the following line would also have worked:
        FILE(GLOB PO_FILES po/*.po)
to
        FILE(GLOB PO_FILES *.po)

But as long as it works, that's the main thing...

One irritating issue (at least on my laptop) is that the contents of the "package/contents/locale" and "package/translations" directories are installed into /usr/share/plasma/plasmoids/org.kde.weatherWidget-2/ when they don't _need_ to be.
It's not a major issue, but it's not ideal.

I'm assuming that's something to do with the "plasma_install_package" line in /CMakeLists.txt, but I can't find any details on what that macro does or how to exclude those directories from the "make install".

I shall add it as a new issue.

**Comment by solbu** [comment]
> I was looking at package/translations/CMakeList.txt - I think changing the following line would also have worked: FILE(GLOB PO_FILES po/*.po) to FILE(GLOB PO_FILES *.po)

I tried that exact change as the first thing I changed, and it results in an Empty package/translations/CMakeList.txt when compiling. So that alone was not working.


> One irritating issue (at least on my laptop) is that the contents of the "package/contents/locale" and "package/translations" directories are installed into /usr/share/plasma/plasmoids/org.kde.weatherWidget-2/ when they don't _need_ to be. It's not a major issue, but it's not ideal.
> 
> I'm assuming that's something to do with the "plasma_install_package" line in /CMakeLists.txt, but I can't find any details on what that macro does or how to exclude those directories from the "make install".

Good catch. The package/translations folder is not needed in an installed system, no.
I'll investigate that a little, and see what can be done.
