### ISSUE TITLE
Need to exclude locale and translations directories from "Make Install"

### ISSUE THREAD

**Issue by blackadderkate** [blackadderkate/weather-widget-2#38]
One irritating issue (at least on my laptop) is that the contents of the "**package/contents/locale**" and "**package/translations**" directories are installed into **/usr/share/plasma/plasmoids/org.kde.weatherWidget-2/** when they don't _need_ to be.
It's not a major issue, but it's not ideal.

As far as I can tell, the following line in CMakeLists.txt is responsible: **plasma_install_package(package org.kde.weatherWidget-2)**
But I can't find any documentation on that Macro.

**Comment by solbu** [comment]
I've been doing som testing.
It seems that the translate folder really do need to stay at the project root folder. when It is move up out of the «package» folder, its content are not included in the install.
I have opened a pull request that fixes at least the translation folder no longer being installed.

**Comment by blackadderkate** [comment]
I have a "hack" for the locale folder too - basically I move it elsewhere at the beginning of the dev-build.sh, and move it back afterwards...

**Comment by solbu** [comment]
According to my testing this morning, your hack is not needed.
It really does install things correctly now.

The dev-build script now only install one copy of the translations, and the plasmoid is also made with only one copy of the translation files.

So I think you do not need to hack this. :-)

**Comment by blackadderkate** [comment]
> According to my testing this morning, your hack is not needed. It really does install things correctly now.
> 
> The dev-build script now only install one copy of the translations, and the plasmoid is also made with only one copy of the translation files.
> 
> So I think you do not need to hack this. :-)

I have a feeling you haven't tried running the "create-plasmoid-package.sh" script first. If you do, you will notice that it compiles all the .po files into package/contents/locale/ - which is correct if you want to distribute the widget on store.kde.org or through "Add Widget".

If you then run "dev-build.sh" (without deleting that locale/ folder beforehand) - it gets included by "make install"  and extra copies of the .mo files are installed when they shouldn't be:
![Screenshot_20220209_143435](https://user-images.githubusercontent.com/83865293/153223017-74c92c32-ba12-49fc-bb4f-cb4f033afb6c.png)

I've had a poke around, and the culprit is the last line of /CMakeLists.txt:  **plasma_install_package(package org.kde.weatherWidget-2)**, which is a macro that just marks the entire contents of the package/ folder for installation - including that unneeded locale folder.
Changing the macro involves hacking files in /usr/lib/x86_64-linux-gnu/cmake/KF5Plasma/, and my CMakeList hacking skills are not good enough to exclude that folder once the macro has marked it for install.

So (unless you are a CMake guru) we have two options:
1. remove the locale/ folder after creating the widget in "create-plasmoid-package.sh".
2. move the locale/ folder elsewhere whilst we compile using "dev-build.sh".

I chose Option 2, as it makes my testing easier...

**Comment by blackadderkate** [comment]
I personally installed the original version of this widget from the "Get New Widgets" button in "Download Widget" - and I am the only user of my laptop - so that was obviously the installation method I focused on. It was also the easiest way to distribute to former users via the KDE store...
I'm obviously delighted at the work you've put into both i18n work, _and_ bundling it for other distributions - thanks for all your efforts - but I am a little concerned about the number of bug reports I might be getting as a result!

**Comment by solbu** [comment]
> I'm obviously delighted at the work you've put into both i18n work, _and_ bundling it for other distributions - thanks for all your efforts - but I am a little concerned about the number of bug reports I might be getting as a result!

Hehe. Been there, done that. :-)
I took over the development of the CD Ripper «grip» on Sourceforge, and I am Not a programmer.
There are plenty of open bug reports that I have no idea how to fix, but soon after the project came back to life, other users came and provided patches, and yet more bug reports. Some of which I could fix as the changes needed to fix them was not much.

My specialy is rpm packaging, and fixing/creating Makefiles and some shellscript hacking. :-)

**Comment by solbu** [comment]
My involvement with this weather project is that I am one of the users of the original weather widget.
and since you came along and launched a fork, and obiously know a little about what needs to be done, I can helt making sure the installation procedures are correct. :-)
