### ISSUE TITLE
An UI widget issue: the temperature value is shifted

### ISSUE THREAD

**Issue by idamir** [blackadderkate/weather-widget-2#41]
The temperature value of the desktop widget is shifted out
![image](https://user-images.githubusercontent.com/4737692/153216722-caba2c09-5997-4b0d-9465-be5ef7dc94f8.png)
v2.2.0

**Comment by blackadderkate** [comment]
I think I have fixed it - please try downloading and installing version 2.2.1 [from here](https://github.com/blackadderkate/weather-widget-2/releases/download/v2.2.1/weather-widget-2.2.1.plasmoid)...

Please let me know if you need any help on how to install/upgrade the widget (or if it doesn't work for some reason) - and don't forget, you'll need to logout and back in again for the upgrade to take effect...

**Comment by idamir** [comment]
Confirm, it is fixed.
