### ISSUE TITLE
An UI widget issue: pressure units are out of meteogram box

### ISSUE THREAD

**Issue by idamir** [blackadderkate/weather-widget-2#49]
In case of using long units they are out of the meteogram box:
![image](https://user-images.githubusercontent.com/4737692/153545017-a9a79234-439b-457b-bc57-0c65683e59a4.png)

What I expect is right adjust of the text:
![image](https://user-images.githubusercontent.com/4737692/153545686-f2811632-e255-4bd1-9662-6ed6a543154b.png)

**Comment by blackadderkate** [comment]
I have uploaded [release v2.2.1a](https://github.com/blackadderkate/weather-widget-2/releases/download/v2.2.1a/weather-widget-2.2.1a.plasmoid) which should fix it.

**Comment by idamir** [comment]
Confirm, it is fixed.
