### ISSUE TITLE
How to translate highlighted items (rainfall)?

### ISSUE THREAD

**Issue by idamir** [blackadderkate/weather-widget-2#51]
![image](https://user-images.githubusercontent.com/4737692/153700214-854fe168-b83e-47c6-a257-52b6dd46b381.png)

**Comment by idamir** [comment]
The 
```
default:
    return unitText
```
is much better than
```
default:
    return ""
```
because it will show that we forget about anything to translate....

**Comment by blackadderkate** [comment]
You're right...

> The
> 
> ```
> default:
>     return unitText
> ```
> 
> is much better than
> 
> ```
> default:
>     return ""
> ```
> 
> because it will show that we forget about anything to translate....

Well spotted. I will fix this.

**Comment by idamir** [comment]
fixed
