### ISSUE TITLE
How do I install it?

### ISSUE THREAD

**Issue by michaldybczak** [blackadderkate/weather-widget-2#58]
I didn't find any proper instruction. I just unpacked the weather-widget-2-master to /.local/share/plasma/plasmoids/.

I found a Weather Widget 2, but when I tried to add it to my latte panel, nothing is happening, so at the moment this plasmoid isn't working for me. I suspect that the installation is at fault. Should I have changed the folder name?

**Comment by blackadderkate** [comment]
Easiest method is through the GUI:

Right-click on the Desktop.
Select Add Widgets. 
At the bottom, select Get New Widgets.
Select Install Widget From Local File.

Or decompress the .widget file in your Download folder, then in the console:
cd <folder name>/package
plasmapkg2 -i .


You might need to delete the folder in .local/share/plasma/plasmoids first...

Hope that helps.

**Comment by blackadderkate** [comment]
I intend to upload it to the KDE store soon (which allows you to add the widget through Discover or the Add Widget option), but every time I think I'm ready, someone finds an obscure bug or uploads a new translation for me to include.

So I never feel like a version is stable enough for "mass release" - if that makes sense...

**Comment by michaldybczak** [comment]
The method of installing it via file doesn't work. Plasma expects to see .plasmoid file, while I have only .zip file from github and no .plasmoid file inside, so basically I can't see anything to install.

The other method is also confusing and not applicable. I don't see any .widget file inside the .zip, so even if I unpack it, what now?

Again, I have weather-widget-2-master.zip from github with all the structure and files from github.

**Comment by blackadderkate** [comment]
Oh, I think I understand the problem - you're downloading the source code, which is for developers.

You need to download the .plasmoid file from the [Releases page](https://github.com/blackadderkate/weather-widget-2/releases) - the link is about halfway down the Github home-page on the right-hand-side.

The latest release .plasmoid file is on there - [version 2.2.2](https://github.com/blackadderkate/weather-widget-2/releases/download/v2.2.2/weather-widget-2.2.2.plasmoid) is the latest...

**Comment by michaldybczak** [comment]
Ah, thanks. Now I see the .plasmoid file. But it seems that adding mechanism from file on Plasma 5.24 is broken.

I see the file and my options are:

Go back - inactive
Go further - inactive
Finish
Cancel

So that leaves me with Finish, which sounds a bit weird, because I can finish the action, meaning, I cancel it, but since there is already cancel button, I hope it means "Add". So I clicked on this Finish and... dialog is gone as expected but without any indication of success. I wanted to add a new widget, but can't find it. I checked /.local/share/plasma/plasmoids/ and, nothing new is there. So it didn't add. What is going on? The whole process is kinda broken in my option or badly designed.

**Comment by blackadderkate** [comment]
OK, let's try it from the Konsole instead.

First delete the folder you created when you unzipped "weather-widget-2-master" - I'm guessing it is called ".local/share/plasma/plasmoids/weather-widget-2-master"?

Then run the following command:

**plasmapkg2 -i ~/Downloads/weather-widget-2.2.2.plasmoid**

The widget should install into the following folder: **~/.local/share/plasma/plasmoids/org.kde.weatherWidget-2**  and you should now be able to see "Weather Widget 2" in the "Add Widget" screen:
![Screenshot_20220216_215831](https://user-images.githubusercontent.com/83865293/154364463-822635b5-fc7a-4f84-adf8-ce15b75a8958.png)

**Comment by blackadderkate** [comment]
Hi.
I'm glad you finally managed to get it installed...


I'm afraid yr.no is obsolete and no longer provides weather data (or meteogram charts) - there's literally no way to get your Yr.no locations to work. The website just doesn't work any more...

So I created this project as an attempt to get a widget that works with the _replacement_ website called met.no. 

Unfortunately the new met.no website and the data it provides is quite different from the old yr.no one - I've done my best to make it look and work as well as the old widget did, but it is not possible to make it exactly the same.

I have tried to make the widget as easy to migrate to as possible though - for example I have included a database and a search engine to help you setup new "met.no" locations...

Hope that helps.

**Comment by solbu** [comment]
Being a norwegian, I can clear up some missunderstanding. yr.no got all their meterological data from met.no.
So the data is the same, just in a different format, or «packaging» if you will.

«Yr» is the norwegian word for «drizzle», as in drizzling rain, yr.no is managed by NRK (Norways equivalent to the BBC) in cooperation with the norwegian Meterological institute.
https://en.wikipedia.org/wiki/Yr.no

**Comment by michaldybczak** [comment]
Thanks for the info, but I couldn't find a forecast on https://www.met.no/en.
When I tried to add the cities in the widget, it showed a lot of cities from my country, but nothing I was searching for. On yr.no, I could find even the smallest places. So far, I can't see that met.no and yr.no data are equal. Anyway, met.no is no way near as friendly as yr.no.

**Comment by blackadderkate** [comment]
I have added installation instructions using various methods - Discover, Add Widgets, and Downloading Manually - in the new "[Discussions](https://github.com/blackadderkate/weather-widget-2/discussions)" area.

I had to make a compromise on the database - I wanted to include the Yr.No database but it is 560Mb in size which is obviously _way_ too big to put in my widget.
It is also _too_ detailed - for example, searching it for "New York" comes up with 15,673 results, and trying to reduce it to a more sensible size proved too difficult. I couldn't figure out a way to distinguish which entries were "important" ones to keep, and which ones were unnecessary duplicates. I think my database contains locations with a population > 500 people...

To make migrating easier, I have now added instructions on how to [migrate your old Yr.No configuration](https://github.com/blackadderkate/weather-widget-2/discussions/64) to the new Widget. Hopefully you will be able to find your location in there!


I think the weird bug you experienced is something to do with focus - once or twice during testing a Dialog box would "lose" focus for unknown reasons. It didn't happen very often - perhaps it is due to the number of Dialog boxes I have open.
I will raise it as a new issue.

**Comment by michaldybczak** [comment]
I was able to add the yr.no data from your migrate your old yr.no guide! It's a workaround, not ideal, but it is working!

I wished the installation and the migration data were to be found on README thou. No idea why the most important data is kept elsewhere. So many packages have nicely formatted README, with: what this project is for, how to install it, uninstall it, FAQ or troubleshot data, and so on. Just look at this:

https://github.com/Askannz/optimus-manager

Of course, this still doesn't contain all possible data, hence the links, but it's a good introduction with the basic data to start with.
