### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by blackadderkate** [blackadderkate/weather-widget-2#6]
Create a plasmoid file, release it on here, and on store.kde.org

**Comment by blackadderkate** [comment]
I have installed this on my laptop, for daily "real-world" testing.
Assuming I don't find any more serious bugs, I will need to create a plasmoid file, upload it to github as a release, and upload it to store.kde.org

One week of daily usage, with no major commits should probably be enough.

**Comment by blackadderkate** [comment]
Published release v2.0.1.
Published release v2.1.0 beta, includes a MET.NO places database and search routine.

**Comment by fkru** [comment]
> Published release v2.0.1. Published release v2.1.0 beta, includes a MET.NO places database and search routine.

Thanks a lot for your efforts to keep the weather plasmoid alive. When do you submit it to kde store?

**Comment by blackadderkate** [comment]
> > Published release v2.0.1. Published release v2.1.0 beta, includes a MET.NO places database and search routine.
> 
> Thanks a lot for your efforts to keep the weather plasmoid alive. When do you submit it to kde store?

Soon!
Hopefully sometime this weekend - I've not submitted anything to the KDE store before, so I don't really know for sure.
I started submitting it last night, but I didn't have any screenshots so I had to give up. :-(

I've grabbed some screenshots now, and hopefully there won't be any more problems.

**Comment by blackadderkate** [comment]
It's been submitted, and is on the KDE store:   [https://store.kde.org/p/1683743](https://store.kde.org/p/1683743).

Assuming I don't receive too many bug reports, I will release the beta version with the built-in searchable database soon.

**Comment by fkru** [comment]
Downloaded version 2.1.4 from KDE store, but  it shows up only in the system tray, which has a different compact layout. What do I miss? Any idea? Thx.

**Comment by blackadderkate** [comment]
> Downloaded version 2.1.4 from KDE store, but  it shows up only in the system tray, which has a different compact layout. What do I miss? Any idea? Thx. 

You probably need to add it to the panel using "add widget", and hide or disable the system tray icon?

**Comment by fkru** [comment]
> > Downloaded version 2.1.4 from KDE store, but  it shows up only in the system tray, which has a different compact layout. What do I miss? Any idea? Thx.
> 
> You probably need to add it to the panel using "add widget", and hide or disable the system tray icon?

I know, which works for other widgets from KDE store as expected, but yours is always stored in the system tray. On top of this, changing the appearance from horizontal to compact does not have any effect. Will investigate this further.

**Comment by blackadderkate** [comment]
I have filed this as a [new Issue](https://github.com/blackadderkate/weather-widget-2/issues/25).
Please can you post any further information / updates there.
Thanks.
