### ISSUE TITLE
Error loading weather-widget-2

### ISSUE THREAD

**Issue by rwt88** [blackadderkate/weather-widget-2#75]
More of a clarification question having never used this or the previous deprecated version of this widget, am I missing a dependency per these error messages?

file:///home/xxxx/.local/share/plasma/plasmoids/org.kde.weatherWidget-2/contents/ui/main.qml:112:5: Type MetNo unavailable

file:///home/xxxx/.local/share/plasma/plasmoids/org.kde.weatherWidget-2/contents/ui/providers/MetNo.qml:2:1: module "QtQuick.XmlListModel" is not installed

Running plasmoidviewer within the directory the widget is stored works but outside of this I keep getting these errors. Any assistance would be appreciated.

**Comment by blackadderkate** [comment]
I have had a quick look at the code, and I don't think I even use xml in that particular module - so I have a feeling that line is completely unnecessary!

I don't have my laptop available at the moment so I can't test it, but I _think_ you should be able to delete line 2 in
/home/xxxx/.local/share/plasma/plasmoids/org.kde.weatherWidget-2/contents/ui/providers/MetNo.qml to fix it... 

But you do need to install the xmllist package if you want to use OpenWeatherMap sources. MYou haven't mentioned which distribution you use, so I can't give you an exact package name, but it is probably called qtquick-xmllistmodel or something very similar...

**Comment by rwt88** [comment]
Commenting out the suggested line and downloading the qt5-xmlpatterns package fixed the issue. Cheers!

**Comment by zsxboli** [comment]
> 

debian11(stable)
To resolve this problem ,which package should i install?

**Comment by zsxboli** [comment]
> > 
> 
> debian11(stable) To resolve this problem ,which package should i install?

Oh,I have resolved this problem .In debian bullseye ,the package name is "qml-module-qtquick-xmllistmodel"
