### ISSUE TITLE
coordinates not numeric in 2.2.4

### ISSUE THREAD

**Issue by jochen-01** [blackadderkate/weather-widget-2#78]
Hi,
after installing the widget with German locale (decimal-comma, not decimal-point) I noticed that the coordinates in longitude and latitude are recognized as "not numeric" shown in red if they have decimal points and not used to build up the url. Changing the decimal separator does not help. 
Had to revert to 2.2.2 to be able to change locations.

We have had it already in the legacy version 2.1.8, you remember?

**Comment by blackadderkate** [comment]
Oh heck. I was convinced I'd applied that fix to the "Master" branch!
I will investigate.

**Comment by blackadderkate** [comment]
Found the bug (and another when tabbing out of the URL box).
I have just uploaded [a new version](https://github.com/blackadderkate/weather-widget-2/releases/download/v2.2.4/weather-widget-2.2.4.1.plasmoid).

**Comment by blackadderkate** [comment]
Rats.
Much better, but it's still not quite right - edit an existing entry still populates the form with period marks in German locales.

**Comment by blackadderkate** [comment]
> Rats. Much better, but it's still not quite right - edit an existing entry still populates the form with period marks in German locales. I will raise a bug for this.

Raised issue #79.

**Comment by blackadderkate** [comment]
I have uploaded [yet another version](https://github.com/blackadderkate/weather-widget-2/releases/download/v2.2.4/weather-widget-2.2.4.2.plasmoid) - I have done some quick testing, and I _think_ it works now...

**Comment by jochen-01** [comment]
> I have uploaded yet another version - I have done some quick testing, and I think it works now...
Link address is incorrect. Should be https://github.com/blackadderkate/weather-widget-2/releases right?

**Comment by blackadderkate** [comment]
Excellent. I will close the issue.

Not sure what happened with the link - it was pretty late when I uploaded the patched version and I was probably tired.
