### ISSUE TITLE
MetNo.qml:130: TypeError: Cannot read property 'summary' of undefined

### ISSUE THREAD

**Issue by solbu** [blackadderkate/weather-widget-2#81]
I don't know when it started, but I noticed today thay my location only has weather info for today and tomorrow, and then it's empty.
Then I also notice it can't seem to fetch updates from met.no.

So I thought that an update to the latest version 2.2.4 might fix it. It did not. :-)
The only change after the update is which line in MetNo.xml triggers the error, but the error message is identical.

I have not changed anything.
I have simply been logged into KDE/Plasma for 30 days. (I never turn off my computers, as they also serves as home servers.)

The syslog entry complains that it can't read something, but opening the URL it uses gields valid data, or at least it looks like it is in Firefox.

Here are the log excerpts.
```
mars 14 16:27:52 mga7-64 plasmashell[8873]: qml: https://api.met.no/weatherapi/sunrise/2.0/.json?lat=64.12361&lon=11.74245&height=29&date=2022-03-14&offset=+01:00
mars 14 16:27:52 mga7-64 plasmashell[8873]: file:///usr/share/plasma/plasmoids/org.kde.weatherWidget-2/contents/ui/providers/MetNo.qml:130: TypeError: Cannot read property 'summary' of undefined
mars 14 16:28:10 mga7-64 plasmashell[8873]: qml: Timed out downloading weather data - aborting attempt. Retrying in 60 seconds time.

mars 14 16:35:18 mga7-64 plasmashell[8873]: qml: https://api.met.no/weatherapi/sunrise/2.0/.json?lat=64.12361&lon=11.74245&height=29&date=2022-03-14&offset=+01:00
mars 14 16:35:19 mga7-64 plasmashell[8873]: file:///usr/share/plasma/plasmoids/org.kde.weatherWidget-2/contents/ui/providers/MetNo.qml:130: TypeError: Type error
mars 14 16:35:40 mga7-64 plasmashell[8873]: qml: Timed out downloading weather data - aborting attempt. Retrying in 60 seconds time.
```

**Comment by blackadderkate** [comment]
Those debug lines are not related to the error, and I need the full debug logs to diagnose the issue.
The easiest method to do this is as follows:

Open the following file:  **/usr/share/plasma/plasmoids/org.kde.weatherWidget-2/contents/ui/main.qml**

Change line 109 to read: `property bool debugLogging: true`
Then in Konsole, kill plasmashell and restart it (or logoff and back in again) - that will enable full debug logging...

Let it run for a couple of minutes, and then please send me the logs...

Note that debug logging is very verbose, so unless you have **lots** of free space on your hard drive, you should probably disable debug logging again after a couple of minutes.

**Comment by solbu** [comment]
For some reaso Github wont allow me to attach a txt file, so I have uploaded the debug log to my website:
https://www.solbu.net/weather-debug-log.txt

**Comment by blackadderkate** [comment]
Odd that it wouldn't allow you to attach the file - perhaps it was too big?

The logfile doesn't provide much useful data - but I did notice one possible cause for your issue:

The URL the weather data is downloaded from is: **https://api.met.no/weatherapi/locationforecast/2.0/compact?lat=64.12361&lon=11.74245&altitude=29**. If you load that URL in Firefox and look at the very last object data, the "next_6_hours" data is missing.

I have a feeling this might be causing the error on your server - although it runs perfectly on my laptop, Perhaps we have different versions of Qt installed, and they behave differently?

Anyway I've come up with [this patch](https://github.com/blackadderkate/weather-widget-2/files/8248414/patch.txt). I've added a bit more debugging information, and added more checks to the code to try and fix the problem.

Please can download the patch and apply it to **/usr/share/plasma/plasmoids/org.kde.weatherWidget-2/contents/ui/providers/MetNo.qml**, and let me know if it fixes the problem.

Thanks.

**Comment by blackadderkate** [comment]
I will close this bug - feel free to reopen it if the issue happens again!
