### ISSUE TITLE
missing wind icons for own 

### ISSUE THREAD

**Issue by KVAnton-WEB** [blackadderkate/weather-widget-2#9]
![изображение](https://user-images.githubusercontent.com/12401787/149585255-767e5e32-fd12-42dd-b42a-41e557c3d321.png)
missing wind icons.

**Comment by blackadderkate** [comment]
Fixed.
You can either [download the fixed version from Github now](https://github.com/blackadderkate/weather-widget-2/releases/download/v2.0.2/weather-widget-2.plasmoid) or wait until I upload it to store.kde.org.
