### ISSUE TITLE
SSL Let's encrypt ceritifcate became obsolete

### ISSUE THREAD

**Issue by michaldybczak** [blackadderkate/weather-widget-2#95]
Today, during system startup I was greeted with error window:
![Screenshot_20220416_125839-2](https://user-images.githubusercontent.com/10132958/163673131-5fa6745a-86ab-4673-ae69-5ce10393fac1.jpeg)

![Screenshot_20220416_121715-2](https://user-images.githubusercontent.com/10132958/163673183-cd14f1a6-7d0a-4a5d-b8d1-96e9fb89e6ca.jpeg)

At first, it was confusing and didn't know where it came from. The window showed Latte Dock, but it made no sense. After an hour, the error messages started poping out every 2 minutes which because incredibly annoying. I couldn't work on a system!

Then I realized, that weather widget 2 is trying to update the weather but can't. I stoped the update and the error windows spam stopped.

Looks like someone forgot to renew SSL Let's encrypt certificate or didn't set up auto-renew of the cerificate :(.

This issue make the whole widget unusable, because the spam messages are highly disturbing and getting in the way of normal system usage. Also without the update, the info is not shown and the widget is not doing its job. Either way, it became useless :(.

**Comment by abuGit** [comment]
This warning is very annoying and  blocks the whole latte. 
![latte-dock-server_2](https://user-images.githubusercontent.com/26663544/163679077-91524c9c-949c-431d-b96e-ed11ca29ca15.png)

**Comment by fkru** [comment]
There is a new certificate by Let's Encrypt valid as of 23 April 2022, so the issue should be fixed. @blackadderkate: Please close as fixed, if the guys don't object.
